### ISSUE TITLE
Metrics module spams during shutdown

### ISSUE THREAD

**Issue by mgobec** [smartcat-labs/cassandra-diagnostics#234]
```
ERROR [metrics-timer] 2017-04-04 08:19:29,732 MetricsCollector.java:133 - Exception while reading attribute Value of type java.lang.Object
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=ThreadPools,path=request,scope=CounterMutationStage,name=ActiveTasks
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[na:1.8.0-zing_16.12.3.0]
...
        at io.smartcat.cassandra.diagnostics.module.metrics.MetricsCollector.collectMeasurements(MetricsCollector.java:124) ~[cassandra-diagnostics-core-1.4.0.jar:na]
        at io.smartcat.cassandra.diagnostics.module.metrics.MetricsModule$MetricsTask.run(MetricsModule.java:66) [cassandra-diagnostics-core-1.4.0.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0-zing_16.12.3.0]
```

There is a ton of these during shutdown sequence.
We should listed to the shutdown event and stop diagnostics modules.

```
INFO  [StorageServiceShutdownHook] 2017-04-04 08:19:26,999 Gossiper.java:1467 - Announcing shutdown
```

**Comment by mgobec** [comment]
@nbozic This should be moved to post 2.0 rework
